### ISSUE TITLE
Consider add a link to Usami-Renko/vulkan-tutorial-rust.

### ISSUE THREAD

**Issue by Usami-Renko** [bwasty/vulkan-tutorial-rs#1]
I find that this repository does similar things compared with my repository [vulkan-tutorial-rust](https://github.com/Usami-Renko/vulkan-tutorial-rust).
The main difference is that the vulkan wrappers we use are different. Both wrappers are low-level.
[Vulkano](https://github.com/vulkano-rs/vulkano) provides a more rust-like API and lots of convenient methods, while [ash](https://github.com/MaikKlein/ash) just keep it lightweight and verbose. 
Would you mind add a inapparent link to my repository in README.md of your repository for those people who prefer using ash ?
Just close this issue if you reject this recommendation for some reasons.

**Comment by bwasty** [comment]
Ok, updated the readme.
