### ISSUE TITLE
VK_LAYER_LUNARG_standard_validation is deprecated

### ISSUE THREAD

**Issue by Nilirad** [bwasty/vulkan-tutorial-rs#28]
`VK_LAYER_LUNARG_standard_validation` is deprecated. Use `VK_LAYER_KHRONOS_validation` instead.

See https://vulkan.lunarg.com/doc/view/1.1.114.0/windows/validation_layers.html

**Comment by Coddeus** [comment]
Updated it here: https://github.com/bwasty/vulkan-tutorial-rs/pull/30
