### ISSUE TITLE
Rework crashes on window resize

### ISSUE THREAD

**Issue by beezir** [bwasty/vulkan-tutorial-rs#3]
Not sure where the issue is, but the code currently crashes for me on swapchain recreate.  It was not doing this with the previous versions of the code.  The following crash occurs using the exact code in the tutorial as of right now.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AccessError { error: SwapchainImageAcquireOnly, command_name: "vkCmdBeginRenderPass", command_param: "attachment 0", command_offset: 0 }', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:511
   6: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:426
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:337
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:92
   9: core::result::unwrap_failed<vulkano::command_buffer::traits::CommandBufferExecError>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, alloc::arc::Arc<vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>, vulkano::command_buffer::traits::CommandBufferExecError>::unwrap<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, alloc::arc::Arc<vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>,vulkano::command_buffer::traits::CommandBufferExecError>
             at C:\projects\rust\src\libcore\result.rs:782
  11: triangletest::HelloTriangleApplication::draw_frame
             at .\src\main.rs:607
  12: triangletest::HelloTriangleApplication::main_loop
             at .\src\main.rs:573
  13: triangletest::main
             at .\src\main.rs:649
  14: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  15: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  16: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  17: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:392
  20: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  21: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  22: main
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  24: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  25: BaseThreadInitThunk
  26: RtlUserThreadStart`

**Comment by bwasty** [comment]
Interesting, will try to look into it later today. Haven't tested on Windows yet, actually.

**Comment by beezir** [comment]
This may be card-specific.  I reran the same built binary on my laptop and it works just fine.   Laptop has Intel GPU, my other computer is nvidia.

**Comment by bwasty** [comment]
Ok, I can reproduce it on macOS/Intel and confirm it worked before the rework - but I don't know what's different yet. And the error seems weird - the comment for it says `Trying to use a swapchain image without depending on a corresponding acquire image future.`, but it's joined just before:
https://github.com/bwasty/vulkan-tutorial-rs/blob/e58aac89377822d480ae0b2a931df7e0366545f7/src/main.rs#L607-L610

**Comment by bwasty** [comment]
Found the problem - see linked commit above.

**Comment by beezir** [comment]
Very nice find, I completely missed that.   

On an unrelated side note found while tinkering with this issue - I may be entirely wrong, but I don't think you need the unsafe device wait line in the swapchain recreation.  Vulkano appears to do all the sync needed with the previous frame cleanup and the passing of the old swapchain during recreation.  I am unfortunately too new in both Rust and Vulkan to know for sure, but it works in my limited testing just fine without any validation errors or crash, and the documentation indicates that you shouldn't generally need to directly call that function.

**Comment by bwasty** [comment]
I went through the Vulkano code and I'm not entirely sure it's safe to omit it, but I removed it now because the docs say that and none of the examples use it either.
